app_code:
    pattern:  /code
    defaults: { _controller: AppCodeBundle:Code:index }

app_code_login:
    pattern: /login
    defaults: { _controller: AppCodeBundle:Code:login }

app_code_login_check:
    pattern: /login_check

app_code_logout:
    pattern: /logout