code:
    pattern:  /code
    defaults: { _controller: AppCodeBundle:code:index }

code_new:
    pattern:  /code/new
    defaults: { _controller: AppCodeBundle:code:new }

code_create:
    pattern:  /code/create
    defaults: { _controller: AppCodeBundle:code:create }

code_show:
    pattern:  /code/{id}
    defaults: { _controller: AppCodeBundle:code:show }

code_edit:
    pattern:  code/{id}/edit
    defaults: { _controller: AppCodeBundle:code:edit }

code_delete:
    pattern:  /delete/{id}
    defaults: { _controller: AppCodeBundle:code:delete }

code_update:
    pattern:  /update/{id}
    defaults: { _controller: AppCodeBundle:code:update }