app_contact:
    resource: "@AppContactBundle/Resources/config/routing.yml"
    prefix:   /

app_product:
    resource: "@AppProductBundle/Resources/config/routing.yml"
    prefix:   /

app_menu:
    resource: "@AppMenuBundle/Resources/config/routing.yml"
    prefix:   /

app_app:
    resource: "@AppAppBundle/Resources/config/routing.yml"
    prefix:   /

