security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
        App\UserBundle\Entity\User: sha512

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        in_memory:
            memory:
                users:
                    sebastien01978: { password: tbk1986!, roles: [ 'ROLE_ADMIN' ] }

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern: ^/
            anonymous: true
            provider: in_memory
            form_login:
                login_path: login
                check_path: login_check
                default_target_path: /admin
            logout:
                path: logout
                target: /

    access_control:
        - { path: ^/contact/, roles: ROLE_ADMIN }
        - { path: ^/toptext, roles: ROLE_ADMIN }
        - { path: ^/product, roles: ROLE_ADMIN }
        - { path: ^/frontbox, roles: ROLE_ADMIN }
        - { path: ^/frontbottom, roles: ROLE_ADMIN }
        - { path: ^/slider, roles: ROLE_ADMIN }
        - { path: ^/menu, roles: ROLE_ADMIN }
        - { path: ^/footer, roles: ROLE_ADMIN }
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/login_check, roles: ROLE_ADMIN }