security:
    encoders:
        Symfony\Component\Security\Core\User\User: sha512

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        main:
            memory:
                users:
                    user: { password: userpass, roles: ['ROLE_USER' ] }
                    admin: { password: adminpass, roles: ['ROLE_ADMIN' ] }

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern: ^/
            anonymous: true
            # provider: main
            # form_login:
            #     login_path: app_code_login
            #     check_path: app_code_login_check
            # logout:
            #     path: app_code_logout
            #     target: /

    access_control:
        - { path: ^/demo/secured/hello/admin/, roles: ROLE_ADMIN }
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
