menu:
    pattern:  /menu
    defaults: { _controller: AppMenuBundle:menu:index }

menu_new:
    pattern:  /menu/new
    defaults: { _controller: AppMenuBundle:menu:new }

menu_create:
    pattern:  /menu/create
    defaults: { _controller: AppMenuBundle:menu:create }

menu_show:
    pattern:  /menu/{id}
    defaults: { _controller: AppMenuBundle:menu:show }

menu_edit:
    pattern:  /menu/{id}/edit
    defaults: { _controller: AppMenuBundle:menu:edit }

menu_delete:
    pattern:  /menu/delete/{id}
    defaults: { _controller: AppMenuBundle:menu:delete }

menu_update:
    pattern:  /menu/update/{id}
    defaults: { _controller: AppMenuBundle:menu:update }