<?php

namespace App\ContactBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TopTextRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TopTextRepository extends EntityRepository
{
}
