<?php

namespace App\ProductBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * FrontBoxRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FrontBoxRepository extends EntityRepository
{
}
